### ISSUE TITLE
Too bright text color

### ISSUE THREAD

**Issue by zlatanvasovic** [shrimp509/shrimp509.github.io#3]
Text color is `#b3b3b3`, which is really bright and unreadable.

With `#111` for example, it looks like this:
![Screenshot from 2020-05-27 16-52-11](https://user-images.githubusercontent.com/2725611/83036202-9cf3eb80-a03a-11ea-94e5-c13ac5d1d366.png)

What do you think?

**Comment by shrimp509** [comment]
OMG, I never think anyone come here. 
Thanks @zdroid , the text color of #111 is much better than before.

**Comment by zlatanvasovic** [comment]
I check your site and noticed the text color, so I found the source of the site here. If you are curious who looks at your website, you can use Google Analytics for that. :wink:

**Comment by shrimp509** [comment]
OK, I'll give it a try to add Google Analytics for this website. Really really really thank you about this !

**Comment by zlatanvasovic** [comment]
You're welcome! Check #4 for my fix
